# Generated by Django 4.1.7 on 2023-12-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_public',
        ),
        migrations.AddField(
            model_name='blog',
            name='display_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Friend Only', 'Friend Only'), ('Public', 'Public')], default='Public', max_length=50),
        ),
    ]
